### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by Bookishi** [indilo53/fivem-es_extended#1]
Can you create a UI for :  https://forum.fivem.net/t/release-jobs-system-v1-0-and-paycheck-v2-0/14054

Like : 
![2017_04_24_20_50_28_2_gtav_rp_13_on_intervient_au_gouvernement_gta_5_youtube](https://cloud.githubusercontent.com/assets/27645538/25353501/be7269b0-292f-11e7-95e4-cc6d281bfb7f.png)

??? :)

**Comment by indilo53** [comment]
Hello, this is already included in es_extended but there is currently no job published. I am working on a policejob right now

**Comment by Bookishi** [comment]
If i install es_extended and add job in db  it's write in left corner ?

**Comment by indilo53** [comment]
Yes

**Comment by indilo53** [comment]
You have to add job_grade in the db too

**Comment by Bookishi** [comment]
I go test and i say you

**Comment by Bookishi** [comment]
Doesn't work 

![2017-04-25 21_07_24-mysql workbench](https://cloud.githubusercontent.com/assets/27645538/25403165/c613fae0-29fb-11e7-9a4a-d75bc7d7825f.png)
![2017-04-25 21_09_24-mysql workbench](https://cloud.githubusercontent.com/assets/27645538/25403166/c631c49e-29fb-11e7-96e2-fef5a2a5a0f3.png)
![2017-04-25 21_09_41-fivereborn server - name_ 5fr 1magnoria city 0 3gta-rp 0 0_ 2 job_p](https://cloud.githubusercontent.com/assets/27645538/25403167/c64da362-29fb-11e7-8a94-e9e0fc5aab42.png)

**Comment by Bookishi** [comment]
![2017-04-25 21_12_13-grand theft auto v](https://cloud.githubusercontent.com/assets/27645538/25403237/081afdee-29fc-11e7-88eb-cdd9d99cda09.png)
![Uploading 2017-04-25 21_12_40-FiveReborn Server - Name_ ^5FR  💼^1Magnoria City  ^0[^3GTA-RP^0]  ^0_  ^2[Job_P.png…]()

**Comment by Bookishi** [comment]
![2017-04-25 21_12_13-grand theft auto v](https://cloud.githubusercontent.com/assets/27645538/25403255/1278f00c-29fc-11e7-91d3-3ee7ac41045b.png)
![2017-04-25 21_12_40-fivereborn server - name_ 5fr 1magnoria city 0 3gta-rp 0 0_ 2 job_p](https://cloud.githubusercontent.com/assets/27645538/25403256/127db844-29fc-11e7-8886-0f272c90f0bd.png)

**Comment by indilo53** [comment]
Have you got errors when importing sql file ?

**Comment by Bookishi** [comment]
nop

**Comment by Bookishi** [comment]
![2017-04-25 21_16_27-mysql workbench](https://cloud.githubusercontent.com/assets/27645538/25403411/8277d846-29fc-11e7-9a85-36527eeba4c9.png)

**Comment by indilo53** [comment]
try to change for RSA at 1

**Comment by indilo53** [comment]
try to change job_id for RSA at 1

**Comment by indilo53** [comment]
if it does't work try to put grade = 0 for CADET

**Comment by Bookishi** [comment]
Okay

**Comment by Bookishi** [comment]
Not work :/

![2017-04-25 21_26_09-grand theft auto v](https://cloud.githubusercontent.com/assets/27645538/25403796/dda2f10a-29fd-11e7-802e-afb6a2a4527e.png)

**Comment by indilo53** [comment]
The items table should contains id (int), name(varchar) and label(varchar) rows, are you sure you had no errors while importing SQL file ?

**Comment by Bookishi** [comment]
i go drop the table and import

**Comment by indilo53** [comment]
dont drop users table

**Comment by indilo53** [comment]
and bans table

**Comment by indilo53** [comment]
it is from es_essential

**Comment by indilo53** [comment]
it is from essentialmode

**Comment by Bookishi** [comment]
no problem ;)

**Comment by Bookishi** [comment]
![2017-04-25 21_40_02-fivereborn server - name_ 5fr 1magnoria city 0 3gta-rp 0 0_ 2 job_p](https://cloud.githubusercontent.com/assets/27645538/25404340/d4eb05aa-29ff-11e7-9fbb-6a8381da921d.png)

**Comment by Bookishi** [comment]
same problem

**Comment by indilo53** [comment]
https://image.ibb.co/iffkD5/Sans_titre.png you should have this structure in your database

**Comment by Bookishi** [comment]
And if the error does not come from your script, the job is don't write on my hud
![2017-04-25 21_41_30-grand theft auto v](https://cloud.githubusercontent.com/assets/27645538/25404403/19189436-2a00-11e7-90c4-b6d83cbbbd6c.png)

**Comment by Bookishi** [comment]
yeah
![2017-04-25 21_42_42-mysql workbench](https://cloud.githubusercontent.com/assets/27645538/25404425/3049bff4-2a00-11e7-885a-d4522fec4899.png)

**Comment by indilo53** [comment]
The error comes from essential mode. I try with a new db to see if I have same bug

**Comment by Bookishi** [comment]
new db essential mode ?

**Comment by Bookishi** [comment]
Ok

**Comment by indilo53** [comment]
I can reproduce the issue. I am working on it.

**Comment by Bookishi** [comment]
Okay ;)

**Comment by indilo53** [comment]
execute the following SQL query

**Comment by indilo53** [comment]
ALTER TABLE `gta5_gamemode_essential`.`users` 
CHANGE COLUMN `job` `job` INT(11) NULL DEFAULT '1' ;

**Comment by indilo53** [comment]
and delete your users or change your users job_id to 1

**Comment by Bookishi** [comment]
Thanks ;)

**Comment by indilo53** [comment]
It works ?

**Comment by Bookishi** [comment]
Yes, just why i can remove the Black money and money and just keep job ?

**Comment by Bookishi** [comment]
and add icon for job ?

**Comment by indilo53** [comment]
You can, just set `Config.accounts = {}` in config.lua and delete saved user_accounts in the db

**Comment by indilo53** [comment]
For the icon this is planned but I have not su much time right now

**Comment by indilo53** [comment]
wait I have to update a bit of code for it to works correctly

**Comment by Bookishi** [comment]
you don't can add icon like for the black money just a icon for all jobs like 💼

**Comment by indilo53** [comment]
I have updated the script, you can download the latest version. I will add icons for different type of jobs, not just one but not now I am working on others scripts

**Comment by Bookishi** [comment]
Thx ;)
