### ISSUE TITLE
Proposition d'amélioration (Mineur)

### ISSUE THREAD

**Issue by Vadrieniel** [indilo53/fivem-es_extended#10]
Hello, je sait que tu à pas mal de boulot pour le moment j'ai lu les autres commentaire :p Je vient juste te proposer un truc peut être simple à mettre en place ? 

Voilà en faite on à l'argent, l'argent sale, l'argent en banque, le titre du métier, ce qui est super je l'avoue mais ce qui serait encore plus top c'est que sa disparaissent quand ont met le jeu en pause afin de voir la liste des divers choses sur la map :)

J'avoue, je ne suis pas venu ici le clavier vide, j'ai trouver un début de code qui permet de cacher l'argent de base, ne peut tu pas l'adapter au reste pour une future maj même lointaine ?

```
    -- Pause menu disable money display
    Citizen.CreateThread(function()
        while true do
            Citizen.Wait(1)
            if IsPauseMenuActive() and not pauseMenu then
                pauseMenu = true
                TriggerEvent('es:setMoneyDisplay', 0.0)
            elseif not IsPauseMenuActive() and pauseMenu then
                pauseMenu = false
                TriggerEvent('es:setMoneyDisplay', 1.0)
            end
        end
    end)
end)
```

Voilà ci cela peut t'aider :) 

Moi je vais le tester de mon coté.

D’ailleurs dans la partie de code ci dessous, c'est une erreur  "exs" au lieu de "esx" ? dans client/main.lua ligne 100

```
RegisterNetEvent("exs:setMoneyDisplay")
AddEventHandler("esx:setMoneyDisplay", function(val)
	SendNUIMessage({
		setDisplay = true,
		display    = val
	})
end)
```
 ?

**Comment by indilo53** [comment]
Merci pour ta contribution je vais voir ca :) C'est exact j'ai fait une erreur

**Comment by indilo53** [comment]
Ca y est c'est fait
