### ISSUE TITLE
Argents sales

### ISSUE THREAD

**Issue by Vadrieniel** [indilo53/fivem-es_extended#13]
Hello, je suis entrain de faire des modification sur un script de braquage, j'aimerais que la recette de la banque ce donne en argents sales, avec l'argent de base j’utilise cette méthode fonctionnel : 

target:addMoney(bank.reward)

Pour l'argent sale j'ai essayer de cette façon : target:addblack_money(bank.reward) mais cela ne fonctionne pas une idée de mon erreur ?

Merci de ton aide.

**Comment by indilo53** [comment]
C'est target:addAccountMoney('black_money', montant)

**Comment by Vadrieniel** [comment]
Ok merci, sauf que moi dans mon cas le montant est défini dans "bank.reward" plus haut afin de pouvoir changer les montants entre chaque banque, je doit faire comment dans ce cas ? Je vient d'essayer de cette façon : target:addAccountMoney('black_money', bank.reward) mais aucun résultat.

**Comment by indilo53** [comment]
Comment récupères-tu la variable du joueur avec esx:getPlayerFromId ?

**Comment by Vadrieniel** [comment]
Non "es:getPlayerFromId" mais sa au besoin je peut faire une modif complète ci je suis sur que cela peut faire fonctionner le système avec l'argent sale

**Comment by indilo53** [comment]
Il faut récupérer avec esx:getPlayerFromId et tu a l'est infos de l'API dans le wiki : https://github.com/indilo53/fivem-es_extended/wiki

**Comment by Vadrieniel** [comment]
Ok je vais faire les modifs nécessaire je revient plus tard, merci.

**Comment by Vadrieniel** [comment]
Hello, c'est re moi :s Voilà j'ai essayer de toute les manière possible soit j'ai une erreur, soit cela ne fonctionne pas, je te montre comment j'ai fait dans le fichier à la ligne 61 (je te le met en .txt) le pire c'est que je doit réglé le problème dans tout les types de braquage que j'ai créer :s Merci.
[server.txt](https://github.com/indilo53/fivem-es_extended/files/998741/server.txt)

**Comment by Vadrieniel** [comment]
C'est bon finalement j'ai fait autrement.
