### ISSUE TITLE
Position sauvegarder ?

### ISSUE THREAD

**Issue by Vadrieniel** [indilo53/fivem-es_extended#14]
Hello, j'ai remarqué que la dernière position était sauvegarder, y a t-il possibilité de retirer cette fonctionnalité ? Je m'explique quand je meurt, je respawn la ou je suis mort, je ne trouve pas la chose très rp :p

Ou tout simplement augmenter le temps avant chaque sauvegarde de position ?

Merci :)

**Comment by SFGamiing** [comment]
Viens sur Teamspeak : ts.groupecampbell.fr ;)

**Comment by indilo53** [comment]
Tu peux commenter la ligne 78 dans client/main.lua 👍 

`TriggerServerEvent('esx:requestLastPosition')`

Quand je trouverais le temps je mettrais le moyen de désactiver dans la config

**Comment by Vadrieniel** [comment]
Ok merci :)
