### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by ig0ne** [indilo53/fivem-es_extended#15]
Petit soucis avec les permissions je pense que ça vient de moi du coup pour utiliser la commande /setjob je dois mettre quoi en permission et ou? 
Moi tout fonctionne trés bien mais quand je met quelqu'un d'autre en owner, 4 il n'as pas accès a /setjob même après reboot et vidage du cache.

**Comment by indilo53** [comment]
Normalement ca devrais fonctionner avec owner, essaie de le mettre en jobmaster pour voir

**Comment by ig0ne** [comment]
j'ai essayer aussi je me demande si j'ai pas un conflit avec un autre mod comme le mode ACL...

**Comment by ig0ne** [comment]
Vraiment désolé tout était de ma faute j'avais sauter une ligne dans la bdd
