### ISSUE TITLE
gb_needs

### ISSUE THREAD

**Issue by ig0ne** [indilo53/fivem-es_extended#17]
Salut, je galère à faire fonctionner ce scripts avec le tiens crois tu pouvoir le modifier ou l'intégré au tiens pour que l'on puisse utiliser les objets de l'inventaire et créer un menu avec les objets dans le magasin? https://github.com/gabsgold/gb_needs

**Comment by TonTonSheitan** [comment]
yo, tu as reussi a le faire fonctionner ? (regarde les issue que j'ai eu avec gab il explique) :)

**Comment by ig0ne** [comment]
nop pas réussi il fonctionne sans le système d'inventaire mais avec je galère

**Comment by TonTonSheitan** [comment]
j'ai reesayer avec l'update de extended mais ya rien a faire sa bloque lol

**Comment by indilo53** [comment]
Bonjour à tous je suis en train de faire un système de faim et soif pour es_extended

**Comment by indilo53** [comment]
J'ai quelque scripts a poster mais je manque de temps désolé je bosse sur 2 serveurs

**Comment by TonTonSheitan** [comment]
ok pas de problème merci pour ta réponse et bon courage a toi ! :)

**Comment by TonTonSheitan** [comment]
@ig0ne yo tu crois ya moyen con mettent le shops (gtarp-sfpd) avec le esx_skin de (indilo53) j'ai essayer mais les vêtement ne ce sauvegarde pas et aucun message d'erreur apparaît. Merci

**Comment by ig0ne** [comment]
Il y a surement moyen mais le soucis c'est qu'il faudrait changer la façon d'appeler les vetements et accessoires et aussi changer la façon dont ça s'enregistre dans la bdd
