### ISSUE TITLE
Exemple use item

### ISSUE THREAD

**Issue by Foxi101** [indilo53/fivem-es_extended#18]
Salut j'ai du mal a comprendre le use item peut tu faire un exemple

Une fois que je les register j'ai pas comprit comment j'attribue une action a cette item ?

**Comment by indilo53** [comment]
esx:registerUsableItem(item, cb)

L'item c'est le nom interne (weed par exemple) et le cb c'est l'action quand tu utilise l'item avec en paramètre la source

ex:

```
TriggerEvent('esx:registerUsableItem', 'weed', function(source)

	local _source = source

	TriggerEvent('esx:getPlayerFromId', _source, function(xPlayer)

		xPlayer:removeInventoryItem('weed', 1)

		TriggerClientEvent('esx:showNotification', _source, 'Vous avez utilisé de la weed')

	end)

end)
```

**Comment by Foxi101** [comment]
Parfait merci !
