### ISSUE TITLE
charger MySql.Data.dll

### ISSUE THREAD

**Issue by Dext25** [indilo53/fivem-es_extended#19]
Bonjour, je n'arrive pas a charger es_extended.
Je le mes dans le dossier ressource voici l'erreur : 
es_extented: Can not call nil value.
Dans le dossier [essential] impossible de charger le fichier MySql.Data.dll
Merci de m'aider pour pouvoir tester votre énorme travail.

**Comment by Geronimin** [comment]
même erreur

**Comment by indilo53** [comment]
Bonjour, il faut le placer dans le dossier [essential]

**Comment by Geronimin** [comment]
essential de base ?

**Comment by indilo53** [comment]
oui le dossier [essential] ou est placé es_admin, es_extended est une extension de essentialmode

**Comment by Geronimin** [comment]
Excuser moi mes je ne voit vraiment pas , sa vous dérangerait de passer sur mon ts3 pour quelque question si vous aver 5-10 minutes ? (91.121.34.32)
