### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by roger55** [indilo53/fivem-es_extended#2]
Hey,

I'm trying to import sql file but it's giving me this error:

#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ADD COLUMN `loadout` LONGTEXT NULL AFTER `job_grade`
ADD COLUMN `position` VARCH' at line 5

I would appreciate a fix for that :)

**Comment by indilo53** [comment]
I add some missing commas, try it now and tell me if it works

**Comment by roger55** [comment]
Thanks you, but there's another error:

 #1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'VALUES (1,'unemployed',0,'rsa','RSA',200,'{}','{}')' at line 1

**Comment by indilo53** [comment]
copy paste this and see if it works

**Comment by indilo53** [comment]
INSERT INTO `job_grades` VALUES (1,'unemployed',0,'rsa','RSA',200,'{}','{}');

CREATE TABLE `jobs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `label` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
);

INSERT INTO `jobs` VALUES (1,'unemployed','Chômeur');

CREATE TABLE `user_accounts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `identifier` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `money` double NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
);

CREATE TABLE `user_inventory` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `identifier` varchar(255) NOT NULL,
  `item` varchar(255) NOT NULL,
  `count` int(11) NOT NULL,
  PRIMARY KEY (`id`)
);

**Comment by roger55** [comment]
Now everything is fine! Thanks 👍

**Comment by indilo53** [comment]
ok :)
