### ISSUE TITLE
Batiment invisible

### ISSUE THREAD

**Issue by frederic2ec** [indilo53/fivem-es_extended#20]
Bonjour,
J'ai quelque probleme avec vos script, plusieurs batiment comme le vendeur de vehicule et l'abattoir sont invisible!

![Vendeur de vehicule](https://i.gyazo.com/896634b025490c1ab47ecaa1d320d0ab.jpg)
![Abattoir](https://i.gyazo.com/3db8a0cc9ed3ce1640e2b7bd9d5f4dbc.jpg)

Merci

**Comment by indilo53** [comment]
Le vendeur de véhicule doit être fixé grace au dernier commit, je regarde pour l'abattoir

**Comment by indilo53** [comment]
téléchargez la dernière version d'esx_garage

**Comment by frederic2ec** [comment]
J'ai régler le sourcis en chargant plusieurs ipl, je te donne ma liste:

>   LoadMpDlcMaps()
  EnableMpDlcMaps(true)
  RequestIpl("chop_props")
  RequestIpl("FIBlobby")
  RemoveIpl("FIBlobbyfake")
  RequestIpl("FBI_colPLUG")
  RequestIpl("FBI_repair")
  RequestIpl("v_tunnel_hole")
  RequestIpl("TrevorsMP")
  RequestIpl("TrevorsTrailer")
  RequestIpl("TrevorsTrailerTidy")
  RemoveIpl("farm_burnt")
  RemoveIpl("farm_burnt_lod")
  RemoveIpl("farm_burnt_props")
  RemoveIpl("farmint_cap")
  RemoveIpl("farmint_cap_lod")
  RequestIpl("farm")
  RequestIpl("farmint")
  RequestIpl("farm_lod")
  RequestIpl("farm_props")
  RequestIpl("facelobby")
  RemoveIpl("CS1_02_cf_offmission")
  RequestIpl("CS1_02_cf_onmission1")
  RequestIpl("CS1_02_cf_onmission2")
  RequestIpl("CS1_02_cf_onmission3")
  RequestIpl("CS1_02_cf_onmission4")
  RequestIpl("v_rockclub")
  RemoveIpl("hei_bi_hw1_13_door")
  RequestIpl("bkr_bi_hw1_13_int")
  RequestIpl("ufo")
  RemoveIpl("v_carshowroom")
  RemoveIpl("shutter_open")
  RemoveIpl("shutter_closed")
  RemoveIpl("shr_int")
  RemoveIpl("csr_inMission")
  RequestIpl("v_carshowroom")
  RequestIpl("shr_int")
  RequestIpl("shutter_closed")
  RequestIpl("smboat")
  RequestIpl("cargoship")
  RequestIpl("railing_start")
  RemoveIpl("sp1_10_fake_interior")
  RemoveIpl("sp1_10_fake_interior_lod")
  RequestIpl("sp1_10_real_interior")
  RequestIpl("sp1_10_real_interior_lod")
  RemoveIpl("id2_14_during_door")
  RemoveIpl("id2_14_during1")
  RemoveIpl("id2_14_during2")
  RemoveIpl("id2_14_on_fire")
  RemoveIpl("id2_14_post_no_int")
  RemoveIpl("id2_14_pre_no_int")
  RemoveIpl("id2_14_during_door")
  RequestIpl("id2_14_during1")
  RequestIpl("coronertrash")
  RequestIpl("Coroner_Int_on")
  RemoveIpl("Coroner_Int_off")
  RemoveIpl("bh1_16_refurb")
  RemoveIpl("jewel2fake")
  RemoveIpl("bh1_16_doors_shut")
  RequestIpl("refit_unload")
  RequestIpl("post_hiest_unload")
  RequestIpl("Carwash_with_spinners")
  RequestIpl("ferris_finale_Anim")
  RemoveIpl("ch1_02_closed")
  RequestIpl("ch1_02_open")
  RequestIpl("AP1_04_TriAf01")
  RequestIpl("CS2_06_TriAf02")
  RequestIpl("CS4_04_TriAf03")
  RemoveIpl("scafstartimap")
  RequestIpl("scafendimap")
  RemoveIpl("DT1_05_HC_REMOVE")
  RequestIpl("DT1_05_HC_REQ")
  RequestIpl("DT1_05_REQUEST")
  RequestIpl("FINBANK")
  RemoveIpl("DT1_03_Shutter")
  RemoveIpl("DT1_03_Gr_Closed")
  RequestIpl("ex_sm_13_office_01a")
  RequestIpl("ex_sm_13_office_01b")
  RequestIpl("ex_sm_13_office_02a")
  RequestIpl("ex_sm_13_office_02b")`

Sa regle le vendeur de vehicule plus l'abattoir!

**Comment by indilo53** [comment]
Oui j'ai la même liste cependant j'aimerais trouver juste les IPLs de l'abattoir

**Comment by frederic2ec** [comment]
Tu pourrais juste mettre tout ces ipl dans ton es_extended, sa permettras d'ouvrir et regler plusieurs espace..

**Comment by indilo53** [comment]
Oui mais je ne veux pas forcer la main aux utilisateurs

**Comment by indilo53** [comment]
Voici les IPLs pour l'abattoir

  RemoveIpl("CS1_02_cf_offmission")
  RequestIpl("CS1_02_cf_onmission1")
  RequestIpl("CS1_02_cf_onmission2")
  RequestIpl("CS1_02_cf_onmission3")
  RequestIpl("CS1_02_cf_onmission4")

**Comment by frederic2ec** [comment]
En voyant tout ce que tu as poster ta pas penser a faire juste un gros mods rp? Disponible en opensource?Sans etre oubliger des installers un apres l'autre

**Comment by indilo53** [comment]
Non je ne veux pas faire un package je laisse les utilisateurs choisir ce qui leur plait

**Comment by indilo53** [comment]
Repo mis à jour avec les IPLs manquant

**Comment by frederic2ec** [comment]
Ha ces ton choix, j'ai peut-etre quelque recommendation comme le chauffeur de taxi, le mineur, les missions de livraison ainsi que la lingerie et le coiffeur. Sa pourrais etre sympas pour completer le tout

**Comment by indilo53** [comment]
Oui c'est prévu mais je manque de temps en ce moment

**Comment by frederic2ec** [comment]
D'accord bonne chance pour la suite!

**Comment by indilo53** [comment]
Merci :)

**Comment by frederic2ec** [comment]
J'ai oublier la nourriture, soif ainsi que le gas sinon tu devrais tout deplacer dans un organisation github sa va etre plus simple pour trouver tout les extensions relier...

**Comment by frederic2ec** [comment]
A la place de le laisser sur ton profil a toi
