### ISSUE TITLE
Problem when I join my server

### ISSUE THREAD

**Issue by DefaltNF** [indilo53/fivem-es_extended#22]
Hello,

When I'm join my server (when es_extended installed) I stay in my loading screen
Client console : 
![](https://i.imgur.com/F21DjZH.png)

Thank's !

**Comment by indilo53** [comment]
What version of essentialmode are you using ?

**Comment by DefaltNF** [comment]
Essential 2.X 
I don't remember the exact version

**Comment by indilo53** [comment]
Have you tried to clear the cache ?

**Comment by DefaltNF** [comment]
Yup

**Comment by Xtrem65** [comment]
please print the content of your "spawnmanager.lua" file (line 108)
