### ISSUE TITLE
Dernière mise à jour broke le serveur.

### ISSUE THREAD

**Issue by Ryload** [indilo53/fivem-es_extended#23]
Si je push la dernière mise à jour, même en mettant l'update DB, le serveur génère une tonne d'erreur à base de object is nil sur quasiment toutes les valeurs. Je reste en version antérieure en attendant de tes nouvelles.

**Comment by indilo53** [comment]
Salut, la colonne name doit avoir un string vide par défaut, pas null c'est peux-être de la que vient le problème

**Comment by Ryload** [comment]
Merci, je regarderai ! Je t'ai fais une issue sur esx_policejob, si tu as le temps de check, j'aimerais rentrer en contact avec toi

**Comment by Ryload** [comment]
![error](https://cloud.githubusercontent.com/assets/27696683/26473027/56602ea6-41a9-11e7-9c56-6d486d7230f3.jpg)

Encore une masse d'erreurs malgré le changement. Tout fonctionne étonnement bien avec l'ancienne pourtant.

**Comment by Ryload** [comment]
![debut](https://cloud.githubusercontent.com/assets/27696683/26473286/db24150c-41aa-11e7-9427-6e8f0314260b.jpg)

Le début de l'erreur, ce qui focus directement la colonne name en effet.

**Comment by Lariime** [comment]
Meme souci, du coup je suis repartie a la version précédente

**Comment by indilo53** [comment]
Comment as-tu réglé ton problème ?

**Comment by Ryload** [comment]
Aucune idée figure toi, Lariime m'a filé son es_extended qui pourtant était vierge aussi, et ça a marché. Et la version via ton github me gênerait des erreurs. Incompréhension totale ahah

**Comment by Lariime** [comment]
Indilo53,, c'est le dev avec qui je travaille qui a pris ta dernière version d'extended, il a modifier juste le HUD pour l'argent, il me la donné. Comme j'avais pas regardé le changelog, je ne savais pas qu'il fallait une nouvelle colonne dans "users", ca a beugué direct, et j'ai juste remis la colonne manuellement via Heidisql, j'ai  aussi supprimé la colonne pour la sauvegarde de nom externe que j'avais installé "nameofplayer" et tout a fonctionné. J'ai filé mon es_extended a Ryload et ca a fonctionné. Au début j'ai eu peur d'avoir donné ton ancienne version mais Ryload ma dit que c'était bon vu que es_extended va bien chercher la nouvelle colonne Name. Je t'avoue qu'hier soir ont a pas compris, mais bon le problème a été réglé. J'ai mi le es_extended de mon serveur sur mon Github si tu veut regardé Indilo ;)

**Comment by indilo53** [comment]
Ok :)
