### ISSUE TITLE
session fantome

### ISSUE THREAD

**Issue by cedricalpatch** [indilo53/fivem-es_extended#24]
Salut

Des problème de session fantôme depuis que j'ai installe le garage apparemment ?
Ou peut etre mon essentialmode qui n'est pas la version 3 ..?

**Comment by indilo53** [comment]
Non c'est bien la version 2 qu'il faut

**Comment by cedricalpatch** [comment]
ok , cela ne viendrait pas du garage ?

**Comment by indilo53** [comment]
Je ne pense pas le garage est utilisé sur 2 serveurs à ma connaissance et je n'ai pas se souci
