### ISSUE TITLE
Erreur lancement serveur

### ISSUE THREAD

**Issue by imThaku** [indilo53/fivem-es_extended#25]
salut j'ai cette erreur au lancement de mon serveur pourrais tu m'aider ?
![preuve](https://cloud.githubusercontent.com/assets/26976347/26528563/5b9367d2-43af-11e7-90a0-b27abe655116.png)

**Comment by indilo53** [comment]
Tu dois placer es_extended dans [essential]

**Comment by imThaku** [comment]
j'ai pas de dossier [essential] j'ai juste sa.

https://gyazo.com/f7c6972a5f8bf12b19a5339f2f309bd4

**Comment by indilo53** [comment]
tu doit créer le dossier [essential] et placer es_extended et es_admin dedans

**Comment by imThaku** [comment]
sa marche merci
