### ISSUE TITLE
Petit bug

### ISSUE THREAD

**Issue by iSlyDz** [indilo53/fivem-es_extended#26]
Salut, j'ai créer un dossier [essential] dans mes ressources, quand je lance le serveur tout va bien, des que je me connecte, je reçoit une tonne d’erreurs dans la console de FiveM server :/

dans le dossier [essential] j'ai seulement mis es_extended et je l'ai déclaré dans citmp-server.yml
et cela ne fonctionne pas du tout :/ 
en plus j'ai aucune icones sur la map, j'ai pas l'argent propres, argents sales, argent sur le compte et le metier en haut a droite de l'écrant
peut tu m'aider stp 

![capture](https://cloud.githubusercontent.com/assets/29024190/26531655/659de890-43ed-11e7-8e0c-2e286cf7903b.JPG)
 petit screen de quand je me co sur le serveur ^^

**Comment by SFGamiing** [comment]
Salut, as tu télécharger l'essential mode ?

**Comment by iSlyDz** [comment]
oui absolument 

![capture](https://cloud.githubusercontent.com/assets/29024190/26531698/dea81a16-43ee-11e7-8884-7cbd1b132795.JPG)

**Comment by iSlyDz** [comment]
si quelqu'un peut venir TeamViwier pour m'aider ça serai cool

**Comment by iSlyDz** [comment]
j'ai réussi c'est bon :)

**Comment by buddyqc** [comment]
Quest que tu as fais pour résoudre ton probleme

**Comment by Xtrem65** [comment]
ta BD est incompatible : "Champ name inconnu dans field list"
