### ISSUE TITLE
Petite question

### ISSUE THREAD

**Issue by Hyakkimaru** [indilo53/fivem-es_extended#27]
Bonjour,

J'utilise actuellement le mod banking pour gérer le système bancaire de mon serveur, est-ce qu'il y a un risque d'incompatibilité avec es_extended vu qu'il semble avoir son propre système de banque lui-aussi ?

Si oui, est-ce qu'une solution est possible pour rallier les deux ? Je pensais faire en sorte que le montant en banque d'es_extended soit égal à celui de banking...

**Comment by nlmarcio** [comment]
moi j'utilise les deux et il y as aucun problème.
a savoir que j'utilise le simplebanking pour la banque
et le system de es_extended pour l'argent sale.
par contre je cherche a faire en sorte que le salaire soit versé dans le simplebanking au lieu de l'argent qu'on as sur soit. si quelqu'un as une solution a cela, je suis preneur :)
