### ISSUE TITLE
Problème avec les véhicules

### ISSUE THREAD

**Issue by Lariime** [indilo53/fivem-es_extended#31]
Salut Indilo.
Je poste ici parce que c'est générale.
Il semble qu'il y a un gros soucis avec les véhicules, a des moments il despawn, même en roulant ou quoi.

Policier, c'est genre un policier sort un véhicules pas forcement le même qu'un autre et d'un coup un des policier en patrouille a son véhicule qui pouf magie noir. ^^

Ca arrive aux personnes qui achète des véhicules aussi, un civil se balade et vu que quelqu'un achète un véhicule pouf il se retrouve a pied.

Pareil pour les métier. 
Ca nous le faisais quand ont avait 4 joueurs, mais la 24 joueurs c'est très dérangeant. Le pire c'est que ca a l'air aléatoire.

**Comment by Xtrem65** [comment]
Si vous trouvez je suis intéressés aussi... ^^

**Comment by indilo53** [comment]
Salut, je n'ai pas de solution actuellement je cherche de temps à autre mais sans succès

**Comment by ig0ne** [comment]
la seul réel piste que j'ai trouvé pour le despawn c'est ce thread: https://forum.fivem.net/t/help-vehicles-keep-despawning/20017/3 mais pas de réel réponse à part de tenter d'adapter le script qui y est partagé à FiveM

**Comment by Xtrem65** [comment]
Ca fait "plaisir" de voir qu'on est pas le seul dans la panade... ^^

Vous avez essayé avec le "true" à "false" ? <= Phrase la moins explicite du monde

Je teste ce soir si jamais ;) je vous tiendrais au jus

**Comment by ig0ne** [comment]
Je ne pense pas que cela fonctionne étant donné que pour les autres métiers " true, false" est présent et j'ai quand même le despawn. de plus l'helico sur le toit spawn quand un joueur s'approche dela zone c'est pour ça que tu le voie tout le temps

**Comment by ig0ne** [comment]
J'ai trouvé ça mais je suis pas sure de leurs fonctions

void SET_VEHICLE_IS_CONSIDERED_BY_PLAYER(Any p0, Any p1)
void SET_PLAYERS_LAST_VEHICLE(Any p0)
void RESERVE_NETWORK_MISSION_VEHICLES(Any p0)
Any GET_NUM_RESERVED_MISSION_VEHICLES(Any p0)

**Comment by Xtrem65** [comment]
C'est vrai que dans le job "trucker" y'a pas ce problème de despawn... si ?

**Comment by ig0ne** [comment]
je crois que non et si j'ai bien compris 
`SetEntityAsNoLongerNeeded` fait en sorte que quand quelqu'un fait spawn un autre véhicule, ça ne fasse pas despawn les anciens.
et `SetVehicleIsConsideredByPlayer` servirais apparemment à rendre le véhicule persistant même quand le joueur n'ai plus dedans.
ce n'est que des suppositions je n'ai essayé

**Comment by Xtrem65** [comment]
du nouveau ?

**Comment by ig0ne** [comment]
pas le temps de tester du coup non

**Comment by Lariime** [comment]
Bon ba moi j'ai mis un autre shop et un autre garage, et même la sur le serveur les véhicules dépop...
Ca doit être dans es_extended, y'a un truc qui va pas.

La c'est ouf. Je pense devoir arrêter extended si je trouve pas une solution rapide, et c'est vraiment dommage :'(

**Comment by ig0ne** [comment]
Je suis pas sur que le problème vienne se extended. J'avais les même soucis avec freeroam essential.

**Comment by Lariime** [comment]
ig0ne , j'ai refait une install propre avec juste du esx dedans, toujours le même souci... Donc moi je pense que ca viens d'extended, je vois pas d'autres explications, 

Indilo est au courant de ce problème donc je pense qu'il se doute que ca vien de extended.
On a essayer de voir aussi avec FiveM France je sais pas si tu connais ce Discord Indilo mais 3 personnes ont essayé de trouvé une solution, sans succes.

Je suis vraiment dégoûté, j'adore extended :(

**Comment by ig0ne** [comment]
comme je t'ai dit avant extended je tournais avec freeroam essential et tous les garages que j'ai pu utiliser il y avais du dépop après tu fais ce que tu veux mais ne soit pas surpris de voir tes véhicules dépop alors que tu n'as plus extended

**Comment by indilo53** [comment]
Apparement ca viendrais du SetEntityAsMissionEntity qui permettrais le despawn de vehicule, je teste de l'enlever pour le policejob sur un serveur et je vous tiens au courant

**Comment by Lariime** [comment]
Merci Indilo c'est super cool ! Moi perso je trouve aucuns "core" qui me convienne depuis que j'ai eu esx pendant 3 semaines ^^

**Comment by Owned3D** [comment]
Allez Indilo Fait nous rever :) <3

**Comment by indilo53** [comment]
Bon sur serveur full aucun dépop aujourd'hui je vous conseille de commenter les SetEntityAsMissionEntity dans vos modules et voir si ca fonctionne, c'est peux-être juste un coup de chance. Si ca fonctionne pour vous j'update le github.

**Comment by Lariime** [comment]
Ils ont tous été passé en commentaire avec "--" du coup, toujours le même problème.

Indilo tu peut me confirmé que tu utilise bien le essentialmode que tu a épinglé dans ton Github ?
Ca a l'air d’être aléatoire le depop, sur le métier de taxi que j'ai fait, avec ton métier d’ambulancier + es_taxi, y'a aucun souci de depop. 
Mais avec les voitures des PNJ, les véhicules acheter, les véhicules spawn via le garage de police ils dépop par la magie noire ^^ 

J'ai jamais eu ce problème avec le métier d'abatteur ni celui de pécheur (ont les a pas testé avec tout le monde qui fait spawn les véhicules de ces métier la.) Je cherche, je cherche mais rien...

Un autre utilisateur de ESX, na aucuns problèmes avec les dépop.
J'ai refait une installation propre avec extended, garage et police, toujours le problème de despawn.

J'ai fait certains essai:
- Un véhicules acheter depop au bout d'un certains nombre de véhicule acheter au Vendeur.
- J'ai acheter une voiture, je l'es garé, j'ai fait un tour de pâté de maison, j'ai pas dépassé les 1km entre la voiture acheter et moi même, je l'es juste "perdu de vue", elle n'était plus la.
- Police: Les véhicules dépop suivant les achat de la police et des joueurs. Ils depop aussi a partir du moment ou les perd de vue.

Indilo possible d'avoir un zip du dossier du serveur qui n'a pas de problème ?
Sans les trucs perso ya pas de souci, je veut juste voir si ca dépop, ayant refait une install propre sans rien de rajouté ca dépop toujours.

Vous avez la colonne "personalvehicle" dans la table "users" ?

**Comment by indilo53** [comment]
Pas besoin d'un dump ton install est bonne c'est juste que ca depop et soit 
mon code est mauvais soit c'est propre à fivem pourtant je me suis 
renseigné sur fivem.net et sur le discord j'ai suivi la procédure qu'on m'a 
donné... Peux être que ca viens de mysql qui bloque le serveur et provoque 
des desync qui font despawn les vehicules, es_extended fait beaucoup de 
requêtes. J'attends la maj fivem pour convertir les acceès à la bdd en 
async et voir ce que ca donne.

Envoyé avec AquaMail pour Android
http://www.aqua-mail.com

**Comment by Lariime** [comment]
10-4 Indilo ^^
Tu a été sur FiveM France voir ? Ya des tètes la bas.

Pour les requêtes avec mysql, extended n'en fait pas plus que les autres... En tout cas quand je regarde dans la console, c'est pas spam H24 par des requêtes.

La MAJ FiveM ? Tu parle de ce qu'ils ont prévue sur Fivem pour qu'on oublie essential ?

**Comment by ig0ne** [comment]
Je pense qu'il parle de la MAJ qui intégreras la gestion de Bdd directement (si je me trompe pas) pour les requêtes MYSQL sync/async il y a un mode si ça peux te servir ==> https://github.com/brouznouf/fivem-mysql-async

**Comment by indilo53** [comment]
Oui j'ai vu cette lib mais je préfère attendre que de réécrire tout le code 2 fois

_Sent from my Samsung SM-G920F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by buddyqc** [comment]
Il y aura t-il de gros changement a faire?

**Comment by indilo53** [comment]
refaire toutes les requêtes MySQL

_Sent from my Samsung SM-G920F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Lariime** [comment]
En utilisant le Lamda Menu pour faire spawn un véhicules, ils ne despawn pas. Meme en allant a l'autre bout de la map. 
On creuse, on creuse.....

**Comment by buddyqc** [comment]
Je suis bon en mysql mais j'apprend le lua

**Comment by Ryload** [comment]
Un possible fix que je suis entrain de tester, j'aurai surement un retour dés demain une fois tous les policiers connectés. 

J'ai modifié le dernier boolean du CreateVehicle en false : 

`local vehicle = CreateVehicle(vehicleModel, coords.x, coords.y, coords.z, 90.0, true, false)
`
Je n'arrive plus à récupérer la documentation détaillée, mais le dernier bool est quasiment toujours set sur false, en tout cas j'ai appris à coder de cette manière, et on le retrouve dans les garages etc de Plysken & co.

Le premier reste en true, car il gère "IsNetwork". J'ai également réactiver SetEntityAsMissionEntity , ce qui, normalement, permet de rendre les véhicules durables.

Feedback prochainement !

**Comment by indilo53** [comment]
J'ai demandé à l'auteur du lambda menu s'il peux me passer le code du spawn véhicule. Je ne suis pas sur qu'il accepte vu que son projet n'est pas open-source.

**Comment by Xtrem65** [comment]
@Ryload j'ai effectué la même modif (false au dernier parametre).

J'ai demandé à la communauté de m'informer si des dépop se reproduisent mais ca a l'air mieux pour l'instant.

**Comment by ig0ne** [comment]
@Xtrem65 @indilo53 @Ryload CreateVehicle avec les deux dernier paramètres en true, false et la réactivation de SetEntityAsMissionEntity semble fonctionner pour le dépop de véhicule. Tester sur un serveur full on à pu noter que seul le spawn de véhicule d'un métier avait eu du dépop et en vérifiant le CreateVehicle était sur true, true. Du coup on continue les tests mais ça semble bien parti.

**Comment by Xtrem65** [comment]
#TeamWork ;)

**Comment by Ryload** [comment]
Yep ! Je confirme aussi qu'une fois les paramètres true, false setup sur chaque vehicle spawner, plus aucun soucis de ce type à signaler. @indilo53 , je pense que j'ai résolu, pardon, ON a résolu, à l'aide de ces gentlemans, le bug principal de ton gamemode !

Dat Teamwork

**Comment by Xtrem65** [comment]
Vous êtes tous des frères pour moi.

Dès que j'ai fini et validé mon garagiste, j'vous le publie ;)

**Comment by indilo53** [comment]
Super ! Bon boulot !

**Comment by Lariime** [comment]
La force des utilisateurs de extended ! :D 
Aller je close merci a tous ca fait plaisir !

Continue Indilo ont est al ! lel
