### ISSUE TITLE
Probleme inventaire

### ISSUE THREAD

**Issue by TonTonSheitan** [indilo53/fivem-es_extended#32]
Salut indilo, juste pour te faire un retour, l'inventaire a quelque problème:

-Quand un joueur et full d'items, un autre joueur a juste a lui donner un item de plus pour que l'inventaire fasse un bug en gros si il et full a 60 et qu'un autre joueur lui en donne 1 et qui passe a 61, ce joueur peu farm a l'infinie. Voila j’espère que j'ai était clair dans mon explication pas évidant a expliquer lol

Merci ;)

**Comment by ig0ne** [comment]
je pense que quand un joueur utilise give item il faudrait vérifier l'inventaire du joueur qui est censé recevoir les objets et annuler la transaction si celui ci est déjà full de cet objet du coup peut être comme dans le vdk inventory ajouter une colone limitation dans la table user_inventory ou peut être mieux dans les items.
Et j'ai eu le même soucis sur mon serveur ou beaucoup en ont profité.

**Comment by indilo53** [comment]
Je vais essayer de voir ca dans la semaine
