### ISSUE TITLE
probleme avec essentialmode et es_extended

### ISSUE THREAD

**Issue by buddyqc** [indilo53/fivem-es_extended#34]
http://prntscr.com/fflrmo

J'ai beau tout faire rien à faire je fais toute ce que vous nous indiquez un peu à droite et à gauche sur votre github et ca ne semble pas fonctionner

**Comment by buddyqc** [comment]
quand j'active es_freeroam comme vous l'indiquer de faire ca bloque à initilizing_session et plus rien ne fonctionne du client

**Comment by Lariime** [comment]
Heu j'ai jamais activé es_freeroam ^^

**Comment by buddyqc** [comment]
Jai du mavoir tromper toutes fonctionne la
