### ISSUE TITLE
Clothe shop

### ISSUE THREAD

**Issue by ig0ne** [indilo53/fivem-es_extended#38]
Salut indilo,
Désolé de te déranger avec ça encore une fois, mais la demande pour un magasin de vêtement se fait de plus en plus forte. Maleurheusement je me perd dans ton code avec esx_skin et skinchanger surtout qu'il y a un .dll dans un des deux scripts. Je voulais savoir si il y avais besoin de ce fameux dll pour pouvoir créer le magasin et si oui est ce possible que tu partage la source? 
J'aimerais savoir un dernier truc, comment tu fais pour enregistrer le skin dans la Bdd?

**Comment by TheGeekGamer91** [comment]
Bonjour, je pense que tu ne l'as pas remarqué mais il a publié le code source de esx_skinchanger. La voici https://github.com/indilo53/fivem-skinchanger/tree/master/skinchanger_dll/skinchanger
Bien entendu vu que c'est une extension dll ce n'est pas du LUA. C'est du C#. Tu devras donc faire avec.
Cordialement, Timothé

**Comment by indilo53** [comment]
Salut ig0ne, je vais travailler sur le magasin de vêtements dans les semaines qui suivent ce sera sour forme d'un menu restreint du skinchanger seulement je m'occupe de 2 serveurs et cela passe en priorité avant le github. De plus étant donné le nombre de rapports de bugs et de demandes je préfère temporiser avant de partager de nouveaux scripts sinon je ne vais plus m'y retrouver. Le source de la dll est publiée sur github dans le repo skinchanger. Le skin est enregistré en json dans la BDD.

```
RegisterServerEvent('esx_skin:savePlayerSkinInfos')
AddEventHandler('esx_skin:savePlayerSkinInfos', function(skin)

	local encodedSkin = json.encode(skin)

	TriggerEvent('esx:getPlayerFromId', source, function(xPlayer)
		MySQL:executeQuery("UPDATE users SET skin = '@skin' WHERE identifier = '@identifier'", {['@identifier'] = xPlayer.identifier, ['@skin'] = encodedSkin})
	end)

end)
```

**Comment by ig0ne** [comment]
Super merci, effectivement je n'avais pas fais attention, et ne t'en fais pas je comprend très bien ta situation, ne crois pas que je te pousse à sortir de nouveaux script plus vite, tu nous à déjà offert une bonne base pour développer d'autres module autour, donc un grand merci à toi ;)

**Comment by indilo53** [comment]
Merci pour le soutient :)
