### ISSUE TITLE
Discord communauté ESX

### ISSUE THREAD

**Issue by Xtrem65** [indilo53/fivem-es_extended#39]
Salut indilo, merci pour ton super boulot.

Ce serait bien d'avoir un discord pour parler entre dev et admins de serveurs "esx"

Qu'en dis tu?

**Comment by indilo53** [comment]
Salut Xtrem65, oui c'est une bonne idée. Saurais-tu le créer ?

**Comment by Xtrem65** [comment]
https://discord.gg/RNeqr

**Comment by Foxi101** [comment]
Pourrait tu refaire une invitation permanente ?

**Comment by Xtrem65** [comment]
Désolé jsuis pas au point avec discord.

On va créer un lien discord.me

En attendant : https://discord.gg/ggjkgTZ 
Valable sans limite de temps jusqu'à 100 utilisations

**Comment by Xtrem65** [comment]
https://discord.me/fivem_esx

Celui ci est illimité :)
