### ISSUE TITLE
Many erros

### ISSUE THREAD

**Issue by roger55** [indilo53/fivem-es_extended#4]
Hey, It seems like there is still a problem.

When I join my server for the first time I can customize my character, money works too, everything is fine, but when I reconnect or just join the server second time everything stops working.

![bvvvv](https://cloud.githubusercontent.com/assets/8419013/25569410/186810b4-2e17-11e7-90aa-58f492fc3cfe.png)

If I want to get this working again I have to reset my whole database.
It seems that there is a problem with reading sql files if there is a user in it.

My database use only essentialmode and esx. 
I'm using the newest files, but it was the same with the previous versions.

AutoStartResources:
    - chat
    - spawnmanager
    - baseevents
    - rconlog
    - hardcap # prevents too many players from joining
    - san_andreas
    - essentialmode
    - es_adminpanel
    - fivem-map-skater
    - es_extended
    - skinchanger
    - esx_skin
    - esx_atm
    - esx_weedjob

**Comment by indilo53** [comment]
Hello, I can't reproduce the issue. Can you provide me a dump of your ressources folder ?

**Comment by indilo53** [comment]
And a dump of your database too

**Comment by roger55** [comment]
Sure - https://github.com/roger55/dump/tree/master/resources

**Comment by indilo53** [comment]
I still cannot repoduce the issue. Can you include your version of essentialmode in the dump ?

**Comment by roger55** [comment]
Done - https://github.com/roger55/dump/tree/master/resources

**Comment by roger55** [comment]
Done - https://github.com/roger55/dump/tree/master/resources/essentialmode

**Comment by indilo53** [comment]
No luck... Try with this version to see if it works for you : https://github.com/kanersps/fivem-essentialmode

I speak about essentialmode because I think some event don't trigger when it should = > es:newPlayerLoaded

**Comment by roger55** [comment]
Yeah! It's working fine now :) Thanks!

btw. you could add a possibility to change the clothes in the clothing shops using menu that we have at the first spawn, and maybe even barber shops where you can change your hair, beard and eyebrows :) I think that would be easy to implement because you already have the whole code. I think that would be really useful :)

**Comment by indilo53** [comment]
Great ! You can type the /skin command if you have owner permission to change your clothes. Barber and clothing shops are planned but I have many things to do right now and can't work on it. I have others scripts but they need more testing before going online like policejob, ambulancejob...
