### ISSUE TITLE
Issue creating tables for 'essentialmode.users'

### ISSUE THREAD

**Issue by SteveTheKing04** [indilo53/fivem-es_extended#41]
When importing the .SQL over and running it, everything else will become port over perfectly fine. Except for the essentialmode.users table. It will tell us that there is no such thing as the table, so I go and create it. But every time I try to create it, it will give me an incorrect syntax error when in reality, there is nothing wrong about it and should run just fine. 

Version of workbench: 6.9.3 or 6.3.9 (either one I believe its the first one)
Sytax error occurs when trying to put this into a table to create the 'essentialmode.users' 

```
CREATE TABLE `users` 
	ADD COLUMN `name` VARCHAR(255) NULL DEFAULT '' AFTER `money`,
	ADD COLUMN `skin` LONGTEXT NULL AFTER `name`,
	ADD COLUMN `job` varchar(255) NULL DEFAULT 'unemployed' AFTER `skin`,
	ADD COLUMN `job_grade` INT NULL DEFAULT 0 AFTER `job`,
	ADD COLUMN `loadout` LONGTEXT NULL AFTER `job_grade`,
	ADD COLUMN `position` VARCHAR(255) NULL AFTER `loadout`
;
```

Email: danielsonke23@gmail.com --Thanks

**Comment by indilo53** [comment]
This is the SQL from essentialmode you need to import the SQL file in esplugin_mysql
