### ISSUE TITLE
Setjob command

### ISSUE THREAD

**Issue by Ykkris** [indilo53/fivem-es_extended#6]
Hey I got an error when I use /setjob

The format is : /setjob [id] [name of job] [grade] 

is it right ? 

Thank you

**Comment by indilo53** [comment]
Yes for example /setjob [id] unemployed 0

**Comment by Ykkris** [comment]
Nope there is an error [https://i.gyazo.com/0902042b97d30414bdc8a3f585a2968e.png](url) when I enter the command it doesn't work

**Comment by indilo53** [comment]
Can you send me an example of what you put for the id ?

**Comment by indilo53** [comment]
You have to take the player server id, the one you see when you press UP arrow in-game, not the identifier in the database

**Comment by Ykkris** [comment]
Yes I take the one who appears when you press the UP arrow in-game. So if ie my mate got the ID n°2 I write /setjob 2 police 0

**Comment by indilo53** [comment]
Can you send me a dump of your jobs and job_grades tables ?

**Comment by indilo53** [comment]
Do you have others errors when connecting or just when using setjob ?

**Comment by Ykkris** [comment]
No error when connecting (can't try another command right now but I'll do it)
[
https://mega.nz/#!qcpGERyb!cXKyVz4fr1jE-b19zNLIbvxYI92an7tKO8AXVyd1UKg
](url) dump of jobs & job_grades tables

**Comment by indilo53** [comment]
Ok your tables looks fine. Can you send me the server error log ? Have you the latest version of es_extended from github ?

**Comment by Ykkris** [comment]
[https://i.gyazo.com/2bb73a22c41074abafb496b04b9c4013.png](url)

I don't know if you used it but here is a discord link [https://discord.gg/Vrutm](url) (btw I'm french too)

**Comment by Ykkris** [comment]
Ok so in order to make the command work you need es_admin !
