### ISSUE TITLE
Delete all inventory

### ISSUE THREAD

**Issue by nlmarcio** [indilo53/fivem-es_extended#7]
Bonjour, je voudrais faire en sorte que l'inventaire soit supprimé lors le personnage meur.
comment je pourrais faire cela?
Merci
******************
Hello, I would like to make sure that the inventory is deleted when the character is dead.
How could I do that?
Thank you

**Comment by indilo53** [comment]
Bonjour, vous pouvez faire quelque chose dans le genre : 

client :
```
local IsAlreadyDead = false

AddEventHandler('playerSpawned', function()
	IsAlreadyDead = false
end)

Citizen.CreateThread(function()
	while true do

		Wait(0)

		local playerPed = GetPlayerPed(-1)

		if IsEntityDead(playerPed) and not IsAlreadyDead then
			TriggerServerEvent('your_namespace:playerDead')
			IsAlreadyDead = true
		end

	end
end)
```

serveur:
```
RegisterServerEvent('your_namespace:playerDead')
AddEventHandler('your_namespace:playerDead', function()

	TriggerEvent('esx:getPlayerFromId', source, function(xPlayer)

		for i=1, #xPlayer.inventory, 1 do

			local item  = xPlayer.inventory[i].item
			local count = xPlayer.inventory[i].count

			xPlayer:removeInventoryItem(item, count)

		end

	end)

end)
```

Je n'ai pas testé ce code il contient peux-être des erreurs mais vous voyez l'idée

**Comment by nlmarcio** [comment]
Parfais merci, je vais voir si je m'en sort avec ça 👍 
Perfect thank you, I'll see if I get away with it 👍

**Comment by nlmarcio** [comment]
Apres avoir testé et modifier pour que cela s’intègre a mon système de mort RP c'est nickel.
au passage la mise a jour de ton es_extended aussi est stylé. je cherchais justement aussi a pouvoir jeter des items par les joueurs. manque plus qu'une petite animation pour que le perso fasse le geste et ça serais nickel ;) et un dernier truc : ça serais cool de pouvoir activer ou pas la sauvegarde auto de la position dans le config.lua, moi je la désactive en manuel mais ça peut toujours servir a d'autres.
Merci pour tout en tout cas :) ça déchire vraiment. Passe faire un tour sur mon serveur si tu veux voir ce que j'ai fait avec ton script ;p (www.nobrain.org)
***************************************************
After testing and modifying so that it fits into my RP death system it is nickel.
In passing the update of your es_extended also is styled. I also wanted to be able to throw items by the players. And a last trick: it would be cool to be able to activate or not the auto backup of the position in the config.lua, I disable it in Manual but it can always be useful to others.
Thanks for everything in any case :) it really tears. If you want to see what I did with your script, p (www.nobrain.org)

**Comment by indilo53** [comment]
Pas de problème merci à toi :)
