### ISSUE TITLE
Dernière question au niveau de l'inventaire.

### ISSUE THREAD

**Issue by nlmarcio** [indilo53/fivem-es_extended#8]
Dernière question et après je te laisse tranquille :)
Compte tu intégré la possibilité aux joueurs de pouvoir donner des items a d'autres joueurs?

**Comment by indilo53** [comment]
Oui c'est prévu :) Je ne sais pas encore quand je vais le faire mais c'est dans la todolist

**Comment by nlmarcio** [comment]
parfait merci, et désolé du dérangement :)

**Comment by indilo53** [comment]
Pas de souci
