### ISSUE TITLE
Erreur M

### ISSUE THREAD

**Issue by Vadrieniel** [indilo53/fivem-es_extended#9]
Hello, voilà pour ne pas te contacter par mail je passe par ici, pourrais tu me dire pourquoi j'ai cette erreur ? Je précise que c'est un serveur de base avec juste essentialmode, es_admin et es_extended. Merci

![1112](https://cloud.githubusercontent.com/assets/28154682/25871133/b9857ad6-3506-11e7-9c8b-2e6bf66c7942.PNG)

**Comment by indilo53** [comment]
Bonsoir, peux tu m'envoyer un copier / coller des 4 premieres lignes de ton es_extended/main.lua ? (en effacant les mots de passe)

**Comment by Vadrieniel** [comment]
Merci de ta rapidité, voilà :)

```
require "resources/[essential]/es_extended/lib/MySQL"
MySQL:open("127.0.0.1", "gta5_gamemode_essential", "root", "coucou")

local Users = {}
```

**Comment by indilo53** [comment]
Pour je ne sais quelle raison le script reconnait MySQL comme une valeur nulle. As-tu bien le dossier lib qui contient bc.dll, MySql.Data.dll et MySQL.lua ?

**Comment by indilo53** [comment]
Ou as-tu placé le dossier es_extended ? dans resources ou dans resources/[essential] ?

**Comment by Vadrieniel** [comment]
Je ne l'avais pas en effet, enfin j'avais le dossier mais pas le contenu, je les re-télécharger j'ai plus cette erreur mais j'en es plein d'autre une fois en jeu, je regarde si le problème ne vient pas de moi puis je repasse. Merci :)

**Comment by indilo53** [comment]
Ok :)

**Comment by indilo53** [comment]
Il ne faut pas oublier d'installer le fichier SQL

**Comment by Vadrieniel** [comment]
Donc voilà, j'ai bien des erreurs mais il y a eu une maj de essentialmode moi j'ai toujours la version d'avant, donc avant de t’embêter le problème ne viendrais pas tout simplement de la ? (Oui j'ai bien mis le sql).
![221122](https://cloud.githubusercontent.com/assets/28154682/25872230/35f7c17a-350a-11e7-8c4a-3617c5e43750.PNG)

**Comment by indilo53** [comment]
Essaie avec cette version du essentialmode, un utilisateur a eu un souci qui c'est réglé avec celle-ci : https://github.com/kanersps/fivem-essentialmode

**Comment by Vadrieniel** [comment]
Super, merci c'est fonctionnel, je vais pouvoir tester tes autres script au passage car je vais repasser mon serveur sous ton script car les autres manque cruellement de mise a jour ... Merci encore pour ton aide & ta rapidité.

**Comment by indilo53** [comment]
Pas de problème, bonne soirée

**Comment by buddyqc** [comment]
j'ai ce genre d'erreur peut-ton avoir le liens vers le essentialmode fonctionnel svp ? merci d'avance
